version: '3'
services:
    app1:
        restart: always
        container_name: app1
        build: .
        depends_on: 
            - db
        ports:
            - 8081
        environment:
            DB_USERNAME: admin
            DB_PASSWORD: admin
            DB_NAME: reservations
            DB_HOST: db
            DB_PORT: 5432
            DB_DIALECT: postgres
            PORT: 8081
            MIGRATE: 1
        networks:
            - app-network
    app2:
        restart: always
        container_name: app2
        build: .
        depends_on: 
            - db
        ports:
            - 8082
        environment:
            DB_USERNAME: admin
            DB_PASSWORD: admin
            DB_NAME: reservations
            DB_HOST: db
            DB_PORT: 5432
            DB_DIALECT: postgres
            PORT: 8082
            MIGRATE: 0
        networks:
            - app-network

    app3:
        restart: always
        container_name: app3
        build: .
        depends_on: 
            - db
        ports:
            - 8083
        environment:
            DB_USERNAME: admin
            DB_PASSWORD: admin
            DB_NAME: reservations
            DB_HOST: db
            DB_PORT: 5432
            DB_DIALECT: postgres
            PORT: 8083
            MIGRATE: 0
        networks:
            - app-network

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: reservations
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        networks:
            - app-network
        restart: unless-stopped

    nginx: 
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app1
            - app2
            - app3
        ports:
             - 80:80
        networks:
            - app-network
    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 8080
        ports:
            - 8080:8080
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
            